language: c
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - libavutil-dev3.3
    - libavformat-dev3.3
    - libavcodec-dev3.3
    - libavdevice-dev3.3
    - libswscale-dev3.3
    - libswresample-dev3.3

script: ./bootstrap && ./configure && make
