language: c
dist: trusty
sudo: true
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get dist-upgrade -q
  - sudo apt-get install ffmpeg -y
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - libavutil-dev
    - libavformat-dev
    - libavcodec-dev
    - libavdevice-dev
    - libswscale-dev

script: ./bootstrap && ./configure && make
